# https://sergiodxa.com/articles/github-actions-npm-publish
# https://github.com/marketplace/actions/get-release-notes

name: gh-pages-deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build:site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DAYSNAP_TOKEN }}
          publish_dir: ./docs-dist
