# https://sergiodxa.com/articles/github-actions-npm-publish
# https://github.com/marketplace/actions/get-release-notes

name: gh-pages-deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    if: "contains(github.event.head_commit.message, '[gh ci]') || contains(github.event.head_commit.message, '[ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Build
        run: |
          node -v
          npm install
          npm run build:site
      - name: Deploy storybook
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/daysnap/daysnap-widgets.git
          npm run deploy:site -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.DAYSNAP_TOKEN }}
