
# https://sergiodxa.com/articles/github-actions-npm-publish
# https://github.com/marketplace/actions/get-release-notes

name: storybook-deploy

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is-new-version: ${{ steps.cpv.outputs.is-new-version }}
      committed-version: ${{ steps.cpv.outputs.committed-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2

  build:
    needs: check
    if: needs.check.outputs.is-new-version == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy storybook
        run: |
          npm run storybook:build
          npm run storybook:deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.DAYSNAP_TOKEN }}
